//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekQuiz.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriviaAnswers
    {
        public int QuestionId { get; set; }
        public int OptionId { get; set; }
        public int Id { get; set; }
        public string UserId { get; set; }
    
        public virtual TriviaOptions TriviaOptions { get; set; }
    }
}
