//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekQuiz.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriviaOptions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TriviaOptions()
        {
            this.TriviaAnswers = new HashSet<TriviaAnswers>();
        }
    
        public int QuestionId { get; set; }
        public int Id { get; set; }
        public string Title { get; set; }
        public bool IsCorrect { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TriviaAnswers> TriviaAnswers { get; set; }
        public virtual TriviaQuestions TriviaQuestions { get; set; }
    }
}
